// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "ded2c03b-5da5-43e0-829e-9dd7c7b78e98";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onFanControlChange();
void onGasLevelChange();
void onTemperatureChange();
void onBuzzerChange();
void onLEDChange();

float Fan_Control;
float Gas_Level;
float Temperature;
bool Buzzer;
bool LED;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(Fan_Control, READWRITE, ON_CHANGE, onFanControlChange);
  ArduinoCloud.addProperty(Gas_Level, READWRITE, ON_CHANGE, onGasLevelChange);
  ArduinoCloud.addProperty(Temperature, READWRITE, ON_CHANGE, onTemperatureChange);
  ArduinoCloud.addProperty(Buzzer, READWRITE, ON_CHANGE, onBuzzerChange);
  ArduinoCloud.addProperty(LED, READWRITE, ON_CHANGE, onLEDChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
